"""empty message

Revision ID: 5c2081888b1e
Revises: 72a98fc465b1
Create Date: 2024-03-09 11:50:06.372472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c2081888b1e'
down_revision = '72a98fc465b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('nivel_acesso')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('nivel_acesso', ['nivel_acesso'], unique=True)

    # ### end Alembic commands ###
