"""empty message

Revision ID: 72a98fc465b1
Revises: cccfa14dba9b
Create Date: 2024-03-09 11:47:42.531024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72a98fc465b1'
down_revision = 'cccfa14dba9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('setor', schema=None) as batch_op:
        batch_op.drop_index('setor')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('setor', schema=None) as batch_op:
        batch_op.create_index('setor', ['setor'], unique=True)

    # ### end Alembic commands ###
