"""empty message

Revision ID: 95a833c03239
Revises: a43186a592c9
Create Date: 2024-03-11 11:22:14.291761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95a833c03239'
down_revision = 'a43186a592c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log_ops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_agenda', sa.Integer(), nullable=True),
    sa.Column('momento_operacao', sa.DateTime(), nullable=False),
    sa.Column('operacao', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('log_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('acesso', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('log_user')
    op.drop_table('log_ops')
    # ### end Alembic commands ###
