"""empty message

Revision ID: a43186a592c9
Revises: 5c2081888b1e
Create Date: 2024-03-10 10:53:46.014347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a43186a592c9'
down_revision = '5c2081888b1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sala', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sala', schema=None) as batch_op:
        batch_op.drop_column('tipo')

    # ### end Alembic commands ###
