"""empty message

Revision ID: cccfa14dba9b
Revises: e4cbe38fca0f
Create Date: 2024-03-07 16:24:22.566925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cccfa14dba9b'
down_revision = 'e4cbe38fca0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('relogio_slots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('em_vigor', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('relogio_slots', schema=None) as batch_op:
        batch_op.drop_column('em_vigor')

    # ### end Alembic commands ###
