"""empty message

Revision ID: d773eb8e4a7a
Revises: 66f8f61a3b50
Create Date: 2024-03-07 14:48:59.930329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd773eb8e4a7a'
down_revision = '66f8f61a3b50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sala',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sala', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sala')
    )
    op.create_table('setor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('setor', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('setor')
    )
    op.create_table('agenda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_sala', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fim', sa.Time(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('dt_cadastro', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_sala'], ['sala.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_setor', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'setor', ['id_setor'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_setor')

    op.drop_table('agenda')
    op.drop_table('setor')
    op.drop_table('sala')
    # ### end Alembic commands ###
