"""empty message

Revision ID: e4cbe38fca0f
Revises: adc1b462e412
Create Date: 2024-03-07 16:07:51.627412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4cbe38fca0f'
down_revision = 'adc1b462e412'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('relogio_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_relogio', sa.String(length=50), nullable=False),
    sa.Column('inicio', sa.Time(), nullable=False),
    sa.Column('fim', sa.Time(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome_relogio')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('relogio_slots')
    # ### end Alembic commands ###
